### ISSUE TITLE
Improve the readme and runbook.

### ISSUE THREAD

**Issue by abstractmachines** [devinenoise/hello-world#7]
include these instructions:

- git clone repo
- cd into that directory
- include a step by step series of instructions for what the user will do. Remember that "launch program" is a specific visual studio thing. Most people won't do that. So you'll need to include instructions for how a user will clone, compile (on the command line), and run your program.
- As always, use the verbiage "prior to this PR, problem X existed, and this PR addresses that by doing Y."
- Remove the "enjoy" from the README text. Tell the user specifically what they're supposed to see "expected output is:" ... Screenshots always helpful! Not of your IDE, but of the output on the command line.
- Please put up a PR and add me as a reviewer.

**Comment by devinenoise** [comment]
Alright, should I fix this after the program full works?

**Comment by abstractmachines** [comment]
Yes.

**Comment by abstractmachines** [comment]
Resolved mostly, by https://github.com/devinenoise/hello-world/pull/10
