### ISSUE TITLE
Restructure your project a bit before proceeding with #5

### ISSUE THREAD

**Issue by abstractmachines** [devinenoise/hello-world#8]
Restructure your project. Comments are embedded in the code (see TODOs). Put up a PR for this before you proceed and add me as a reviewer.

After you do each small step, compile and run the code, add a commit, and push it up. Again, you'll need a fresh branch.

```
// TODO 1: Delete this line. You don't need it. numGroup isn't used anywhere.
// Then compile and run your code.
int numGroup[5] = { 1, 3, 5, 7, 9 };

// TODO 2: Delete these lines. All you're doing is declaring a function by expressing the "function signature" here. 
// Then compile and run your code. If it doesn't run, then do TODO 4, below, then compile and run.
string helloWorld();
void numberArray();

int main() {

   cout << helloWorld(); 

     
   numberArray();

   // TODO 3: Delete this line. We aren't getting user input yet.
// Then compile and run your code.
   system("pause>0");
    
}


/* TODO 4: Remove these definitions to the TOP of your file right after your imports. */
//define helloWorld()
string helloWorld() {
    return "Hello World!\n";
}

// define numberArray() to loop through numGroup
void numberArray() {
    for (int i = 0; i < 5; i++) {
        cout << numGroup[i] << endl;
    }
}
```

**Comment by abstractmachines** [comment]
# To understand why we're making these changes: 

@devinenoise:
- [ ]  read about the difference between "declaring a function" and "defining a function", 
- [ ] and read about "invoking or calling a function." 
- [ ] Finally, read about what a "function signature" is and what a "function body" is. 
- [ ] Type up your readings and understanding and add them in README as part of your PR to demonstrate your understanding of the above 4-5 concepts.

> More detail:

Declaring the functions above with merely a function signature without a function body (such as `string helloWorld();` and `void numberArray();` ) is an unnecessary operation. Just define your functions before your main() function.

https://www.cprogramming.com/declare_vs_define.html

**Comment by devinenoise** [comment]
numGroup is used to loop through the numberArray function.  If I delete it the function doesn't work.  I think I need to define the function differently to hold any array but I forgot how.

**Comment by abstractmachines** [comment]
> numGroup is used to loop through the numberArray function.  If I delete it the function doesn't work.  I think I need to define the function differently to hold any array but I forgot how.  

That's what was confusing me. Okay, so a function should be self contained. If you need to loop through something within a function, all of that should happen within the function @devinenoise
